### PR TITLE
Remove echo agent pid from env file (SOFTWARE-4729)

### PR DESCRIPTION
**Pull request by mtru32**

### CODE REVIEW

**Review by brianhlin — COMMENTED** [review]
This seems like a potentially brittle solution: what if the line ordering of the `oidc-agent` output changes? You're probably better off stripping out any `echo` lines by piping `oidc-agent` through `grep -v`

**Review by brianhlin — APPROVED** [review]
LGTM but I'd like you to verify that this works @mtru32! Let me know if you need help with that process

**Comment by mtru32** [comment]
I ran the container and can confirm the echo lines are removed from /tmp/oidc-agent.env. Also, I don't see any extra output when making calls to oidc-*. @brianhlin

**Review by brianhlin — APPROVED** [review]
LGTM!

**Pull request merged**
